name: 'Dependabot PR Automation'
description: 'Parse Dependabot commit metadata to automate PR handling'
inputs:
  github-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
outputs:
  updated-dependencies:
    description: 'A JSON serialised hash of any metadata found in verified Dependabot commits in the PR.'
runs:
  using: 'node14'
  main: 'dist/index.js'
